<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Ashok" failures="3" tests="15" name="Test" time="0.106" errors="0" timestamp="2022-03-02T09:34:00 IST">
  <testcase classname="seleniumTests.RetryFailedTestcases" name="test1" time="0.013">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase classname="seleniumTests.RetryFailedTestcases" name="test1" time="0.001">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase classname="seleniumTests.RetryFailedTestcases" name="test1" time="0.001">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase classname="seleniumTests.RetryFailedTestcases" name="test1" time="0.002">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase classname="seleniumTests.RetryFailedTestcases" name="test1" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at seleniumTests.RetryFailedTestcases.test1(RetryFailedTestcases.java:16)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase classname="seleniumTests.RetryFailedTestcases" name="test2" time="0.001">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase classname="seleniumTests.RetryFailedTestcases" name="test2" time="0.0">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase classname="seleniumTests.RetryFailedTestcases" name="test2" time="0.002">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase classname="seleniumTests.RetryFailedTestcases" name="test2" time="0.001">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase classname="seleniumTests.RetryFailedTestcases" name="test2" time="0.001">
    <failure type="java.lang.ArithmeticException" message="/ by zero">
      <![CDATA[java.lang.ArithmeticException: / by zero
at seleniumTests.RetryFailedTestcases.test2(RetryFailedTestcases.java:21)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase classname="seleniumTests.RetryFailedTestcases" name="test3" time="0.001">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase classname="seleniumTests.RetryFailedTestcases" name="test3" time="0.001">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase classname="seleniumTests.RetryFailedTestcases" name="test3" time="0.001">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase classname="seleniumTests.RetryFailedTestcases" name="test3" time="0.002">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase classname="seleniumTests.RetryFailedTestcases" name="test3" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at seleniumTests.RetryFailedTestcases.test3(RetryFailedTestcases.java:27)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
</testsuite> <!-- Test -->
